{{- if .Values.global.enableLogging }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tp-dp-monitor-agent.consts.appName" . }}-fluentbit-config
  labels:
    {{- include "tp-dp-monitor-agent.shared.labels.standard" . | nindent 4 }}
data:
  fluent-bit.conf: |
    [SERVICE]
      Flush             1
      Log_Level         info
      Daemon            off
      Parsers_File      parsers.conf

    @INCLUDE input.conf
    @INCLUDE filter.conf
    @INCLUDE output.conf

  input.conf: |
    [INPUT]
      Name              tail
      Tag               tp.${POD_NAMESPACE}.${POD_NAME}.${POD_ID}.${CONTAINER_NAME}
      Path              /var/log/pods/${POD_NAMESPACE}_${POD_NAME}_${POD_ID}/${CONTAINER_NAME}/*.log
      multiline.parser  docker, cri
      DB                /var/log/flb_kube.db
      Mem_Buf_Limit     5MB
      Skip_Long_Lines   On
      Refresh_Interval  10

  filter.conf: |
    [FILTER]
      Name              record_modifier
      Match             tp.*
      Record            host.ip ${HOST_IP}
      Record            kubernetes.pod.name ${POD_NAME}
      Record            kubernetes.pod.uid ${POD_ID}
      Record            kubernetes.namespace ${POD_NAMESPACE}
      Record            kubernetes.container.name ${CONTAINER_NAME}
      Remove_key        stream
      Remove_key        _p
      Remove_key        date
    [FILTER]
      Name              parser
      Match             tp.*
      Key_Name          log
      Parser            json_decode
      Reserve_Data      True
    [FILTER]
      Name              nest
      Match             tp.*
      Operation         lift
      Nested_Under      log
      Add_prefix        log.
    [FILTER]
      Name              modify
      Match             tp.*
      Rename            log.timestamp @timestamp
      Rename            log.msg message
      Rename            log.file source
    [FILTER]
      Name              nest
      Match             tp.*
      Operation         nest
      Nest_Under        kubernetes.pod
      Wildcard          kubernetes.pod.*
      Remove_prefix     kubernetes.pod.
    [FILTER]
      Name              nest
      Match             cic20.*
      Operation         nest
      Nest_Under        kubernetes.container
      Wildcard          kubernetes.container.*
      Remove_prefix     kubernetes.container.
    [FILTER]
      Name              nest
      Match             cic20.*
      Operation         nest
      Nest_Under        kubernetes
      Wildcard          kubernetes.*
      Remove_prefix     kubernetes.
    [FILTER]
      Name              nest
      Match             cic20.*
      Operation         nest
      Nest_Under        cic.installation
      Wildcard          cic.installation.*
      Remove_prefix     cic.installation.
    [FILTER]
      Name              nest
      Match             cic20.*
      Operation         nest
      Nest_Under        cic.cluster
      Wildcard          cic.cluster.*
      Remove_prefix     cic.cluster.
    [FILTER]
      Name              nest
      Match             cic20.*
      Operation         nest
      Nest_Under        cic.kubernetes
      Wildcard          cic.kubernetes.*
      Remove_prefix     cic.kubernetes.
    [FILTER]
      Name              nest
      Match             cic20.*
      Operation         nest
      Nest_Under        cic
      Wildcard          cic.*
      Remove_prefix     cic.
    [FILTER]
      Name              nest
      Match             cic20.*
      Operation         nest
      Nest_Under        cloud.account
      Wildcard          cloud.account.*
      Remove_prefix     cloud.account.
    [FILTER]
      Name              nest
      Match             cic20.*
      Operation         nest
      Nest_Under        cloud
      Wildcard          cloud.*
      Remove_prefix     cloud.
    [FILTER]
      Name              nest
      Match             cic20.*
      Operation         nest
      Nest_Under        host
      Wildcard          host.*
      Remove_prefix     host.
    [FILTER]
      Name              nest
      Match             cic20.*
      Operation         nest
      Nest_Under        log
      Wildcard          log.*
      Remove_prefix     log.

  output.conf: |
{{- if .Values.global.finops }}
{{- if .Values.global.finops.logServer }}
{{- if and (.Values.global.finops.logServer.default) }}
    [OUTPUT]
      Name              es
      Match             tp.*
      Trace_Error       On
      Host              {{ .Values.global.finops.logServer.host }}
      Port              {{ .Values.global.finops.logServer.port }}
{{- if .Values.global.finops.logServer.scheme }}
{{- if eq .Values.global.finops.logServer.scheme "https" }}
      tls               On
      tls.verify        Off
{{- end }}
{{- end }}
      Index             {{ .Values.global.finops.logServer.default.index }}
      HTTP_User         ${LOG_SERVER_USERNAME}
      HTTP_Passwd       ${LOG_SERVER_PASSWORD}
{{- else }}
    [OUTPUT]
      Name              stdout
      Match             tp.*
      Format            json
      json_date_key     @timestamp
{{- end }}
{{- else }}
{{- /* we are missing the global.finops.logServer section */}}
    [OUTPUT]
      Name              stdout
      Match             tp.*
      Format            json
      json_date_key     @timestamp
{{- end }}
{{- else }}
{{- /* we are missing the global.finops section */}}
    [OUTPUT]
      Name              stdout
      Match             tp.*
      Format            json
      json_date_key     @timestamp
{{- end }}

  parsers.conf: |
    [PARSER]
      Name              json_decode
      Format            regex
      Regex             ^(?<log>.*)$
      Time_Key          time
      Time_Format       %Y-%m-%dT%H:%M:%S.%L
      Time_Keep         On
      Decode_Field_As   json log

{{- end }}